-- Create subscribers table for email list
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  source TEXT NOT NULL DEFAULT 'signup_form' CHECK (source IN ('signup_form', 'testimonial', 'contact')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'unsubscribed')),
  confirmation_token TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  confirmed_at TIMESTAMP WITH TIME ZONE
);

-- Index for fast email lookups
CREATE INDEX IF NOT EXISTS idx_subscribers_email ON subscribers(email);
CREATE INDEX IF NOT EXISTS idx_subscribers_status ON subscribers(status);

-- Enable Row Level Security
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;

-- Public can insert (subscribe)
CREATE POLICY "Anyone can subscribe" ON subscribers
  FOR INSERT WITH CHECK (true);

-- Public can update their own subscription (confirm/unsubscribe via token)
CREATE POLICY "Anyone can confirm via token" ON subscribers
  FOR UPDATE USING (true)
  WITH CHECK (status IN ('confirmed', 'unsubscribed'));

-- Admins can view all subscribers
CREATE POLICY "Admins can view subscribers" ON subscribers
  FOR SELECT USING (
    auth.role() = 'authenticated' AND
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND is_admin = TRUE
    )
  );

-- Admins can delete subscribers
CREATE POLICY "Admins can delete subscribers" ON subscribers
  FOR DELETE USING (
    auth.role() = 'authenticated' AND
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND is_admin = TRUE
    )
  );

-- Function: upsert subscriber (used by testimonial/contact flows)
-- Inserts if new, updates source if already exists, never downgrades status
CREATE OR REPLACE FUNCTION upsert_subscriber(
  p_email TEXT,
  p_name TEXT DEFAULT NULL,
  p_source TEXT DEFAULT 'signup_form'
) RETURNS subscribers AS $$
DECLARE
  v_subscriber subscribers;
BEGIN
  INSERT INTO subscribers (email, name, source, status, confirmation_token)
  VALUES (
    p_email,
    p_name,
    p_source,
    'pending',
    encode(gen_random_bytes(32), 'hex')
  )
  ON CONFLICT (email) DO UPDATE SET
    name = COALESCE(EXCLUDED.name, subscribers.name),
    source = CASE
      WHEN subscribers.status = 'unsubscribed' THEN subscribers.source  -- don't change source if unsubscribed
      ELSE EXCLUDED.source
    END,
    -- Keep confirmed status if already confirmed; otherwise set to pending (re-subscribe)
    status = CASE
      WHEN subscribers.status = 'confirmed' THEN 'confirmed'
      WHEN subscribers.status = 'unsubscribed' THEN 'unsubscribed'  -- don't re-subscribe someone who unsubscribed
      ELSE 'pending'
    END,
    confirmation_token = CASE
      WHEN subscribers.status = 'pending' THEN subscribers.confirmation_token  -- keep existing token
      ELSE encode(gen_random_bytes(32), 'hex')  -- new token
    END
  RETURNING * INTO v_subscriber;

  RETURN v_subscriber;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
